<template>
  <div class="game-page">
    <NavigationHeader 
      class="navigation"
      v-model:search-term="searchTerm"
      @search="onSearch"
      :loading="searchLoading"
    />

    <!-- Loading State -->
     <div v-if="loading" class="loading-spinner">
      <Spinner message="Searching for game reports..." />
    </div>

    <!-- Error State -->
    <ErrorMessage :message="error" @dismiss="clearError" class="error-with-top-margin" />

    <!-- Not a game item State -->
    <div v-if="game && !isGameType && !loading && !error">
      <WarningMessage :message="`This is not a video game! You may be looking for ${game?.steam_app?.fullgame?.name || 'another item'} instead.`" />
      <GameDescription :game="game" />
      <p v-if="game?.steam_app?.fullgame?.appid" class="parent-game-link">
        View original game:
        <router-link
          class="parent-game-link__cta"
          :to="{ name: 'Game', params: { gameId: game.steam_app.fullgame.appid } }"
        >
          {{ game?.steam_app?.fullgame?.name || `App ${game.steam_app.fullgame.appid}` }}
        </router-link>
      </p>
    </div>

    <!-- Game ready State -->
     <div v-if="game && isGameType && !pendingGame && !loading && !error">
      <GameDescription :game="game" />
      <AskAICard 
        class="settings-section" 
        :title="`What is the community saying?`"
        :animate-text="true"
        :content="aiCardContent"
        :type-speed="15"
        :start-delay="800"
        @feedback="submitCurrentGameSummaryVote"
      >
      </AskAICard>
      <GameReportsSection v-if="game.reports" :reports="game.reports" />
      <AddReport :game-id="gameId" />
    </div>

    <!-- Processing State -->
    <div v-if="isGameType && pendingGame && !loading && !error">
      <ProcessingWarning :game-name="gameTitle" />
      <div class="refresh-button-container">
        <RefreshButton :countdown-start="60" />
      </div>
      <RandomArt />
    </div>
    </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, toRef, watch } from 'vue'
import { useNuxtApp, useRouter } from '#imports'
import Spinner from '../components/base/Spinner.vue'
import AskAICard from '../components/common/AskAICard.vue'
import ErrorMessage from '../components/common/ErrorMessage.vue'
import RandomArt from '../components/common/RandomArt.vue'
import RefreshButton from '../components/common/RefreshButton.vue'
import WarningMessage from '../components/common/WarningMessage.vue'
import AddReport from '../components/ui/AddReport.vue'
import GameDescription from '../components/ui/GameDescription.vue'
import GameReportsSection from '../components/ui/GameReportsSection.vue'
import NavigationHeader from '../components/ui/NavigationHeader.vue'
import ProcessingWarning from '../components/ui/ProcessingWarning.vue'
import type { GameDetails, GameId, GameReportData } from '../components/ui/types'

interface FetchGameResponse {
  status: 'queued' | 'ready' | 'invalid'
  game: GameDetails
}

defineOptions({ name: 'GamePage' })

const props = defineProps<{
  gameId: string
}>()

const { $backendApi } = useNuxtApp()
const router = useRouter()
const gameId = toRef(props, 'gameId')

const game = ref<GameDetails | null>(null)
const loading = ref(false)
const error = ref<string | null>(null)
const searchPerformed = ref(false)
const processingWarning = ref(false)
const pendingGame = ref(false)
const searchLoading = ref(false)
const searchTerm = ref('')

function getReportTimestamp(postedAt: GameReportData['posted_at']): number {
  if (!postedAt) return 0
  return postedAt instanceof Date ? postedAt.getTime() : new Date(postedAt).getTime()
}

function getErrorMessage(error: unknown): string {
  if (error instanceof Error) return error.message
  if (typeof error === 'object' && error !== null && 'message' in error) {
    const message = error.message
    if (typeof message === 'string') return message
  }
  return String(error)
}

const gameTitle = computed<string>(() => game.value?.steam_app?.name || `Game ID ${gameId.value}`)

const isGameType = computed<boolean>(() => game.value?.steam_app?.type === 'game')

const aiCardContent = computed<string>(() => {
  if (!game.value?.game_performance_summary) return ''

  const summary = game.value.game_performance_summary
  const disclaimer =
    '\n\n<i>This is a brief summary of community feedback generated by AI and may contain errors.\nPlease refer to the community reports for accurate information.</i>'

  return summary + disclaimer
})

const isInInputField = (target: EventTarget | null): boolean => {
  // Check if the target element is an input field where backspace should work normally
  if (!(target instanceof HTMLElement)) return false
  const inputTypes = ['INPUT', 'TEXTAREA', 'SELECT']
  return inputTypes.includes(target.tagName) || target.contentEditable === 'true'
}

const handleKeydown = (event: KeyboardEvent): void => {
  // Check if backspace key is pressed and not in an input field
  if (event.key === 'Backspace' && !isInInputField(event.target)) {
    event.preventDefault()
    router.back()
  }
}

const onSearch = (): void => {
  if (!searchTerm.value) return
  searchLoading.value = true
  // redirect to search results page with delay
  setTimeout(() => {
    searchLoading.value = false
    void router.push({ name: 'SearchResults', query: { q: searchTerm.value } })
  }, 300)
}

const clearError = (): void => {
  error.value = null
}

const updateDocumentTitle = (): void => {
  document.title = `${gameTitle.value} - Steam Deck Reports`
}

const loadGame = async (): Promise<void> => {
  if (!gameId.value) {
    error.value = 'Unknown game ID.'
    return
  }

  loading.value = true
  error.value = null
  game.value = null
  searchPerformed.value = true
  pendingGame.value = false

  try {
    const res = (await $backendApi.fetchGame(gameId.value)) as FetchGameResponse

    if (res.status === 'queued') {
      pendingGame.value = true
      game.value = res.game
      return
    }

    const sortedReports = [...(res.game.reports ?? [])].sort((a, b) => {
      return getReportTimestamp(b.posted_at) - getReportTimestamp(a.posted_at)
    })

    game.value = { ...res.game, reports: sortedReports }
  } catch (err: unknown) {
    error.value = getErrorMessage(err)
  } finally {
    loading.value = false
  }
}

const submitGameSummaryVote = async (gameId: GameId, feedback: unknown): Promise<void> => {
  const voteType = feedback === 'positive' ? 'up' : feedback === 'negative' ? 'down' : null
  if (!voteType) return

  try {
    await $backendApi.submitGameSummaryVote(gameId, voteType)
  } catch (error) {
    console.error('Error submitting game summary vote:', error)
  }
}

const submitCurrentGameSummaryVote = async (feedback: unknown): Promise<void> => {
  const currentGameId = game.value?.game_id
  if (currentGameId == null) return
  await submitGameSummaryVote(currentGameId, feedback)
}

watch(
  gameId,
  () => {
    void loadGame()
  },
  { immediate: true }
)

watch(gameTitle, updateDocumentTitle, { immediate: true })

onMounted(() => {
  // Add keyboard event listener for backspace key
  document.addEventListener('keydown', handleKeydown)
})

onUnmounted(() => {
  // Remove keyboard event listener to prevent memory leaks
  document.removeEventListener('keydown', handleKeydown)
})
</script>

<style scoped>
.game-page {
  width: 100%;
}

.navigation {
  margin-bottom: 40px;
}

.settings-section {
  margin-top: 20px;
}

.parent-game-link {
  margin: 20px 0 0;
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
  color: var(--text-secondary);
}

.parent-game-link__cta {
  display: inline-flex;
  align-items: center;
  border: 1px solid var(--secondary-border-color);
  background: var(--bg-secondary);
  color: var(--text-primary);
  padding: 6px 12px;
  border-radius: 999px;
  text-decoration: none;
  font-weight: 600;
  transition: border-color 0.2s ease, background-color 0.2s ease, color 0.2s ease;
}

.parent-game-link__cta:hover {
  border-color: var(--primary-color);
  color: var(--primary-color);
  background: var(--primary-bg-active);
}

.parent-game-link__cta:focus-visible {
  outline: 2px solid var(--primary-color);
  outline-offset: 2px;
}

.error-with-top-margin {
  margin-top: 20px;
}

.loading-spinner {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 50vh;
}

.steam-login-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 0;
}

.game-data-sources {
  margin-bottom: 2rem;
}

.steam-login-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 0;
  display: flex;
  align-items: center;
}

.refresh-button-container {
  margin: 1rem 0 2rem 0;
  text-align: center;
}

@media (max-width: 768px) {
  .navigation {
    margin-bottom: 20px;
  }
}
</style>
