<template>
  <div class="game-page">
    <NavigationHeader 
      class="navigation"
      v-model:search-term="searchTerm"
      @search="onSearch"
      :loading="searchLoading"
    />

    <!-- Loading State -->
     <div v-if="loading" class="loading-spinner">
      <Spinner message="Searching for game reports..." />
    </div>

    <!-- Error State -->
    <ErrorMessage :message="error" @dismiss="clearError" class="error-with-top-margin" />

    <!-- Not a game item State -->
    <div v-if="game && !isGameType && !loading && !error">
      <WarningMessage :message="`This is not a video game! You may be looking for ${game?.steam_app?.fullgame?.name || 'another item'} instead.`" />
      <GameDescription :game="game" />
      <p v-if="game?.steam_app?.fullgame?.appid" class="parent-game-link">
        View original game:
        <router-link
          class="parent-game-link__cta"
          :to="{ name: 'Game', params: { gameId: game.steam_app.fullgame.appid } }"
        >
          {{ game?.steam_app?.fullgame?.name || `App ${game.steam_app.fullgame.appid}` }}
        </router-link>
      </p>
    </div>

    <!-- Game ready State -->
     <div v-if="game && isGameType && !pendingGame && !loading && !error">
      <GameDescription :game="game" />
      <AskAICard 
        class="settings-section" 
        :title="`What is the community saying?`"
        :animate-text="true"
        :content="aiCardContent"
        :type-speed="15"
        :start-delay="800"
        @feedback="submitCurrentGameSummaryVote"
      >
      </AskAICard>
      <GameReportsSection v-if="game.reports" :reports="game.reports" />
      <AddReport :game-id="gameId" />
    </div>

    <!-- Processing State -->
    <div v-if="isGameType && pendingGame && !loading && !error">
      <ProcessingWarning :game-name="gameTitle" />
      <div class="refresh-button-container">
        <RefreshButton :countdown-start="60" />
      </div>
      <RandomArt />
    </div>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Spinner from '../components/base/Spinner.vue'
import AskAICard from '../components/common/AskAICard.vue'
import ErrorMessage from '../components/common/ErrorMessage.vue'
import RandomArt from '../components/common/RandomArt.vue'
import RefreshButton from '../components/common/RefreshButton.vue'
import WarningMessage from '../components/common/WarningMessage.vue'
import AddReport from '../components/ui/AddReport.vue'
import GameDescription from '../components/ui/GameDescription.vue'
import GameReportsSection from '../components/ui/GameReportsSection.vue'
import NavigationHeader from '../components/ui/NavigationHeader.vue'
import ProcessingWarning from '../components/ui/ProcessingWarning.vue'
import type { GameDetails, GameId, GameReportData } from '../components/ui/types'

interface FetchGameResponse {
  status: 'queued' | 'ready' | 'invalid'
  game: GameDetails
}

interface GamePageState {
  game: GameDetails | null
  loading: boolean
  error: string | null
  searchPerformed: boolean
  processingWarning: boolean
  pendingGame: boolean
  searchLoading: boolean
  searchTerm: string
}

function getReportTimestamp(postedAt: GameReportData['posted_at']): number {
  if (!postedAt) return 0
  return postedAt instanceof Date ? postedAt.getTime() : new Date(postedAt).getTime()
}

function getErrorMessage(error: unknown): string {
  if (error instanceof Error) return error.message
  if (typeof error === 'object' && error !== null && 'message' in error) {
    const message = error.message
    if (typeof message === 'string') return message
  }
  return String(error)
}

export default defineComponent({
  name: 'GamePage',
  components: {
    AddReport,
    GameDescription,
    GameReportsSection,
    ProcessingWarning,
    ErrorMessage,
    Spinner,
    RefreshButton,
    RandomArt,
    AskAICard,
    NavigationHeader,
    WarningMessage,
  },
  props: {
    gameId: {
      type: String,
      required: true,
    },
  },
  data(): GamePageState {
    return {
      game: null,
      loading: false,
      error: null,
      searchPerformed: false,
      processingWarning: false,
      pendingGame: false,
      searchLoading: false,
      searchTerm: '',
    }
  },
  computed: {
    gameTitle(): string {
      return this.game?.steam_app?.name || `Game ID ${this.gameId}`
    },
    isGameType(): boolean {
      return this.game?.steam_app?.type === 'game'
    },
    aiCardContent(): string {
      if (!this.game?.game_performance_summary) return ''

      const summary = this.game.game_performance_summary
      const disclaimer =
        '\n\n<i>This is a brief summary of community feedback generated by AI and may contain errors.\nPlease refer to the community reports for accurate information.</i>'

      return summary + disclaimer
    },
  },
  watch: {
    gameId: {
      immediate: true,
      handler() {
        this.loadGame()
      },
    },
  },
  async mounted() {
    // Add keyboard event listener for backspace key
    document.addEventListener('keydown', this.handleKeydown)
    this.updateDocumentTitle()
  },
  unmounted() {
    // Remove keyboard event listener to prevent memory leaks
    document.removeEventListener('keydown', this.handleKeydown)
  },
  methods: {
    handleKeydown(event: KeyboardEvent) {
      // Check if backspace key is pressed and not in an input field
      if (event.key === 'Backspace' && !this.isInInputField(event.target)) {
        event.preventDefault()
        this.$router.back()
      }
    },

    onSearch() {
      if (!this.searchTerm) return
      this.searchLoading = true
      // redirect to search results page with delay
      setTimeout(() => {
        this.searchLoading = false
        this.$router.push({ name: 'SearchResults', query: { q: this.searchTerm } })
      }, 300)
    },

    isInInputField(target: EventTarget | null): boolean {
      // Check if the target element is an input field where backspace should work normally
      if (!(target instanceof HTMLElement)) return false
      const inputTypes = ['INPUT', 'TEXTAREA', 'SELECT']
      return inputTypes.includes(target.tagName) || target.contentEditable === 'true'
    },

    clearError() {
      this.error = null
    },

    updateDocumentTitle() {
      document.title = `${this.gameTitle} - Steam Deck Reports`
    },

    async loadGame() {
      if (!this.gameId) {
        this.error = 'Unknown game ID.'
        return
      }

      this.loading = true
      this.error = null
      this.game = null
      this.searchPerformed = true
      this.pendingGame = false

      try {
        const res = (await this.$backendApi.fetchGame(this.gameId)) as FetchGameResponse

        if (res.status === 'queued') {
          this.pendingGame = true
          this.game = res.game
          return
        }

        const sortedReports = [...(res.game.reports ?? [])].sort((a, b) => {
          return getReportTimestamp(b.posted_at) - getReportTimestamp(a.posted_at)
        })

        this.game = { ...res.game, reports: sortedReports }
      } catch (err: unknown) {
        this.error = getErrorMessage(err)
      } finally {
        this.loading = false
      }
    },
    async submitGameSummaryVote(gameId: GameId, feedback: unknown) {
      const voteType = feedback === 'positive' ? 'up' : feedback === 'negative' ? 'down' : null
      if (!voteType) return

      try {
        await this.$backendApi.submitGameSummaryVote(gameId, voteType)
      } catch (error) {
        console.error('Error submitting game summary vote:', error)
      }
    },
    async submitCurrentGameSummaryVote(feedback: unknown) {
      const gameId = this.game?.game_id
      if (gameId == null) return
      await this.submitGameSummaryVote(gameId, feedback)
    },
  },
})
</script>

<style scoped>
.game-page {
  width: 100%;
}

.navigation {
  margin-bottom: 40px;
}

.settings-section {
  margin-top: 20px;
}

.parent-game-link {
  margin: 20px 0 0;
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
  color: var(--text-secondary);
}

.parent-game-link__cta {
  display: inline-flex;
  align-items: center;
  border: 1px solid var(--secondary-border-color);
  background: var(--bg-secondary);
  color: var(--text-primary);
  padding: 6px 12px;
  border-radius: 999px;
  text-decoration: none;
  font-weight: 600;
  transition: border-color 0.2s ease, background-color 0.2s ease, color 0.2s ease;
}

.parent-game-link__cta:hover {
  border-color: var(--primary-color);
  color: var(--primary-color);
  background: var(--primary-bg-active);
}

.parent-game-link__cta:focus-visible {
  outline: 2px solid var(--primary-color);
  outline-offset: 2px;
}

.error-with-top-margin {
  margin-top: 20px;
}

.loading-spinner {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 50vh;
}

.steam-login-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 0;
}

.game-data-sources {
  margin-bottom: 2rem;
}

.steam-login-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 0;
  display: flex;
  align-items: center;
}

.refresh-button-container {
  margin: 1rem 0 2rem 0;
  text-align: center;
}

@media (max-width: 768px) {
  .navigation {
    margin-bottom: 20px;
  }
}
</style>
